# Generated by Django 2.2.14 on 2022-07-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField()),
                ('transaction_type', models.CharField(max_length=10)),
                ('open_position', models.BooleanField()),
                ('order_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('price_in', models.FloatField()),
                ('side', models.CharField(max_length=20)),
                ('time_out', models.DateTimeField()),
                ('price_out', models.FloatField(default=0)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.CharField(default='0', max_length=20)),
                ('buy_facter', models.IntegerField(default=300)),
                ('sell_factor', models.IntegerField(default=0)),
                ('TP1', models.IntegerField(default=40)),
                ('TP2', models.IntegerField(default=90)),
                ('time_out', models.IntegerField(default=60)),
                ('percentage_premium', models.FloatField(default=0.99)),
                ('lot', models.IntegerField(default=1)),
                ('order_type', models.CharField(default='MARKET', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='SOME STRING', max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=25)),
                ('angel_api_keys', models.CharField(default='SOME STRING', max_length=100)),
                ('angel_client_id', models.CharField(default='SOME STRING', max_length=10)),
                ('angel_password', models.CharField(default='SOME STRING', max_length=10)),
            ],
        ),
    ]
