# Generated by Django 2.2.14 on 2022-07-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='buy_facter',
            new_name='buy_factor',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='order_type',
        ),
        migrations.AddField(
            model_name='strategy',
            name='LIMIT',
            field=models.CharField(default='off', max_length=8),
        ),
    ]
