# Generated by Django 2.2.14 on 2022-07-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0002_auto_20220718_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='token',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='strategy',
            name='ET',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='expiry_1',
            field=models.CharField(default='NA', max_length=12),
        ),
        migrations.AddField(
            model_name='strategy',
            name='expiry_2',
            field=models.CharField(default='NA', max_length=12),
        ),
        migrations.AddField(
            model_name='strategy',
            name='expiry_selected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='spot',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='status',
            field=models.CharField(default='OPEN', max_length=8),
        ),
        migrations.AddField(
            model_name='strategy',
            name='v_factor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='working_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='open_position',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='positions',
            name='price_in',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='positions',
            name='side',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='positions',
            name='status',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='positions',
            name='strategy_id',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='positions',
            name='symbol',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='positions',
            name='time_out',
            field=models.DateTimeField(default=0),
        ),
    ]
