# Generated by Django 2.2.14 on 2022-07-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0003_auto_20220720_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='expiry_1',
            field=models.CharField(default='NA', max_length=12),
        ),
        migrations.AddField(
            model_name='user1',
            name='expiry_2',
            field=models.CharField(default='NA', max_length=12),
        ),
        migrations.AddField(
            model_name='user1',
            name='working_days',
            field=models.IntegerField(default=0),
        ),
    ]
