# Generated by Django 2.2.14 on 2022-07-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0005_auto_20220721_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='T1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='T2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='T3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='T4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='T5',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='T_now',
            field=models.IntegerField(default=3),
        ),
    ]
