# Generated by Django 4.0.6 on 2022-08-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0006_auto_20220721_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='current_price',
            field=models.FloatField(default=0),
        ),
    ]
