# Generated by Django 4.0.6 on 2022-09-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0007_positions_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='pnl',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='pnl',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user1',
            name='pnl',
            field=models.FloatField(default=0),
        ),
    ]
