# Generated by Django 4.0.6 on 2022-09-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0008_positions_pnl_strategy_pnl_user1_pnl'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='buy_nifty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='nifty_current',
            field=models.FloatField(default=0),
        ),
    ]
